### ISSUE TITLE
WebUI port not exposed?

### ISSUE THREAD

**Issue by reinhard-brandstaedter** [Dynatrace/Dynatrace-AppMon-Docker#13]
It seems that the AppMon webUI port (9911, default) is not exposed and thus the webui is not reachable from the outside/host.
I suggest adding this additional port to the config.

**Comment by MarcinZejer** [comment]
Hi Reinhard, 
Thanks for problem identification. We will address that.
Marcin

**Comment by MarcinZejer** [comment]
Fixed in commit https://github.com/Dynatrace/Dynatrace-AppMon-Docker/commit/3be8cd40b55ed9aa8016869009c183395d7acede
