### ISSUE TITLE
Invalid or Corrupt jarfile

### ISSUE THREAD

**Issue by shahzadmasud** [Dynatrace/Dynatrace-AppMon-Docker#16]
I am getting below message while execute 'docker-compose up'. 

Error: Invalid or corrupt jarfile /tmp/dynatrace-server-7.0.0.2469-linux-x86.jar
ERROR: Service 'dtserver' failed to build: The command '/bin/sh -c apk update && apk add --no-cache ${DT_INSTALL_DEPS} ${DT_RUNTIME_DEPS} &&     curl --insecure -L -o /tmp/${INSTALLER_FILE_NAME} ${INSTALLER_URL} && 	java -jar /tmp/${INSTALLER_FILE_NAME} -b 64 -t ${DT_HOME} -y && 	apk del ${DT_INSTALL_DEPS} && 	rm -rf /tmp/*' returned a non-zero code: 1

**Comment by thomas-klambauer** [comment]
Could be related to https://github.com/Dynatrace/Dynatrace-AppMon-Puppet/issues/39
The dynatrace-server-X file is an internal-only artifact and was removed. Should be switched to the -full- file. see other ticket.

Actually you should get a 404 when trying to download that file.

**Comment by MarcinZejer** [comment]
We will address that issue this week. Thank you for your help

**Comment by MarcinZejer** [comment]
Docker hub images have been also updated

**Comment by shahzadmasud** [comment]
Looks like space runs out, 

========
docker-compose up
Building dtserver
Step 1/24 : FROM alpine:3.5
 ---> 4a415e366388
Step 2/24 : LABEL maintainer "Martin Etmajer <martin.etmajer@dynatrace.com>"
 ---> Using cache
 ---> 6994ca8a5d3c
Step 3/24 : LABEL maintainer2 "Blazej Tomaszewski <blazej.tomaszewski@dynatrace.com>"
 ---> Using cache
 ---> 5426cc46a30b
Step 4/24 : ARG DT_HOME
 ---> Using cache
 ---> 46224ea2ae01
Step 5/24 : ARG BUILD_VERSION
 ---> Using cache
 ---> 95557dd084bb
Step 6/24 : ARG VERSION
 ---> Using cache
 ---> 412a2a2b2316
Step 7/24 : ARG DT_SERVER_LICENSE_KEY_FILE_URL
 ---> Using cache
 ---> 2aa184f94df2
Step 8/24 : ENV INSTALLER_FILE_NAME dynatrace-full-${BUILD_VERSION}-linux-x86-64.jar
 ---> Using cache
 ---> a8ab159e56cf
Step 9/24 : ENV INSTALLER_URL https://files.dynatrace.com/downloads/OnPrem/dynaTrace/${VERSION}/${BUILD_VERSION}/${INSTALLER_FILE_NAME}
 ---> Using cache
 ---> c2d9ca17d3ad
Step 10/24 : ENV DT_INSTALL_DEPS openjdk8-jre-base
 ---> Using cache
 ---> deca1d32d572
Step 11/24 : ENV DT_RUNTIME_DEPS bash\ curl
 ---> Using cache
 ---> 86aadcc95ddc
Step 12/24 : RUN apk update && apk add --no-cache ${DT_INSTALL_DEPS} ${DT_RUNTIME_DEPS} &&     curl --insecure -L -o /tmp/${INSTALLER_FILE_NAME} ${INSTALLER_URL} && 	java -jar /tmp/${INSTALLER_FILE_NAME} -b 64 -t ${DT_HOME} -y && 	apk del ${DT_INSTALL_DEPS} && 	rm -rf /tmp/*
 ---> Running in b3518c4d4934
fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/community/x86_64/APKINDEX.tar.gz
v3.5.2-184-g09b259c295 [http://dl-cdn.alpinelinux.org/alpine/v3.5/main]
v3.5.2-177-gfdf1237bb5 [http://dl-cdn.alpinelinux.org/alpine/v3.5/community]
OK: 7966 distinct packages available
fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/community/x86_64/APKINDEX.tar.gz
(1/31) Installing ncurses-terminfo-base (6.0-r8)
(2/31) Installing ncurses-terminfo (6.0-r8)
(3/31) Installing ncurses-libs (6.0-r8)
(4/31) Installing readline (6.3.008-r4)
(5/31) Installing bash (4.3.46-r5)
Executing bash-4.3.46-r5.post-install
(6/31) Installing ca-certificates (20161130-r1)
(7/31) Installing libssh2 (1.7.0-r2)
(8/31) Installing libcurl (7.55.0-r0)
(9/31) Installing curl (7.55.0-r0)
(10/31) Installing openjdk8-jre-lib (8.121.13-r0)
(11/31) Installing java-common (0.1-r0)
(12/31) Installing libffi (3.2.1-r2)
(13/31) Installing libtasn1 (4.9-r2)
(14/31) Installing p11-kit (0.23.2-r1)
(15/31) Installing p11-kit-trust (0.23.2-r1)
(16/31) Installing java-cacerts (1.0-r0)
(17/31) Installing libjpeg-turbo (1.5.1-r0)
(18/31) Installing krb5-conf (1.0-r1)
(19/31) Installing libcom_err (1.43.3-r0)
(20/31) Installing keyutils-libs (1.5.9-r1)
(21/31) Installing libverto (0.2.5-r0)
(22/31) Installing krb5-libs (1.14.3-r1)
(23/31) Installing lcms2 (2.8-r1)
(24/31) Installing nspr (4.12-r0)
(25/31) Installing sqlite-libs (3.15.2-r0)
(26/31) Installing nss (3.28.4-r0)
(27/31) Installing pcsc-lite-libs (1.8.20-r0)
(28/31) Installing lksctp-tools (1.0.17-r0)
(29/31) Installing libgcc (6.2.1-r1)
(30/31) Installing libstdc++ (6.2.1-r1)
(31/31) Installing openjdk8-jre-base (8.121.13-r0)
ERROR: Failed to create usr/lib/jvm/java-1.8-openjdk/jre/lib/amd64/server/libjvm.so: No space left on device
ERROR: openjdk8-jre-base-8.121.13-r0: No space left on device
Executing busybox-1.25.1-r0.trigger
Executing ca-certificates-20161130-r1.trigger
Executing java-common-0.1-r0.trigger
1 errors; 68 MiB in 41 packages
ERROR: Service 'dtserver' failed to build: The command '/bin/sh -c apk update && apk add --no-cache ${DT_INSTALL_DEPS} ${DT_RUNTIME_DEPS} &&     curl --insecure -L -o /tmp/${INSTALLER_FILE_NAME} ${INSTALLER_URL} && 	java -jar /tmp/${INSTALLER_FILE_NAME} -b 64 -t ${DT_HOME} -y && 	apk del ${DT_INSTALL_DEPS} && 	rm -rf /tmp/*' returned a non-zero code: 1

**Comment by MarcinZejer** [comment]
Hi @shahzadmasud,

I have built again docker images with docker-compose. I think something is wrong with your environment. 

Regards,
Marcin

**Comment by shahzadmasud** [comment]
fixed, thank you.
