### ISSUE TITLE
Script templates should not use "curl --insecure" by default

### ISSUE THREAD

**Issue by thomas-klambauer** [Dynatrace/Dynatrace-AppMon-Docker#17]
This disables certificate validation, which makes the user vulnerable to MITM attacks injecting malicious code when downloading installer files.

Consider using one global configuration flag for this and have it set to a "secure" state, which the user can override at his own risk (note that risk in comments).

Also, the current certificate for files.dynatrace.com should be un-problematic and widely checkable as it's CA is available in all current JDKs, browser and OS cert stores.

Contact me if you think we can improve something on the files.dynatrace.com server / certificate side.

**Comment by MarcinZejer** [comment]
Thanks Thomas, we will address that

**Comment by MarcinZejer** [comment]
Fixed in:
cbace01e7322ed7113e92e24386902c1d30da2c8
45f7afa36df6909214ec96dc5b89c8a0ef47671e
