### ISSUE TITLE
Use as non-privileged container

### ISSUE THREAD

**Issue by Lain92** [Dynatrace/Dynatrace-AppMon-Docker#18]
Hello,

Is it possible to use the dockerized Dynatrace server as a non-root user?
CaaS users cannot run privileged containers on the platform so that would mean we cannot use Dynatrace for containers at all.

When DT server is run in Openshift, it crashloops.
```
/opt/dynatrace/run-server-process.sh: line 2: /opt/dynatrace/dtfrontendserver: Permission denied
/opt/dynatrace/run-server-process.sh: line 3: /opt/dynatrace/dtserver: Permission denied
```

Cheers,

Lain92

**Comment by BlazejT** [comment]
@Lain92 

Possibility of running Dynatrace Appmon services as non-root user is added in [514cd34b44](https://github.com/Dynatrace/Dynatrace-AppMon-Docker/commit/514cd34b44abb8ea2603c09cfbf8a1ca90bb6edf) commit.

Let us know if it does work for you.

Thanks,
BT

**Comment by Lain92** [comment]
Hi @BlazejT,

Thank you very much for your implementation, it covers our need perfectly.

Sincerely,

Raphael
