### ISSUE TITLE
Buildfile error

### ISSUE THREAD

**Issue by omerlin** [Dynatrace/Dynatrace-AppMon-Docker#21]
Hello, 
on Redhat 7.2, i have this error during the build:

> Step 22/30 : RUN apk update && apk add --no-cache ${DT_INSTALL_DEPS} ${DT_RUNTIME_DEPS} &&      mkdir -p ${DT_HOME} &&      /usr/bin/install-agent.sh ${AGENT_INSTALLER_URL} &&      /usr/bin/install-wsagent.sh ${WSAGENT_INSTALLER32_URL} &&      /usr/bin/install-wsagent.sh ${WSAGENT_INSTALLER64_URL} &&      /usr/bin/install-node-agent.sh ${NODE_AGENT_INSTALLER_URL} &&        mkdir -p ${DT_HOME}/log/agent &&       apk del ${DT_INSTALL_DEPS}
>  ---> Running in 39f643abb838
> fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/main/x86_64/APKINDEX.tar.gz
> fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/community/x86_64/APKINDEX.tar.gz
> v3.5.2-225-g4d15b3991f [http://dl-cdn.alpinelinux.org/alpine/v3.5/main]
> v3.5.2-213-g0860a961bc [http://dl-cdn.alpinelinux.org/alpine/v3.5/community]
> OK: 7964 distinct packages available
> fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/main/x86_64/APKINDEX.tar.gz
> fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/community/x86_64/APKINDEX.tar.gz
> (1/31) Installing ncurses-terminfo-base (6.0_p20170701-r0)
> (2/31) Installing ncurses-terminfo (6.0_p20170701-r0)
> (3/31) Installing ncurses-libs (6.0_p20170701-r0)
> (4/31) Installing readline (6.3.008-r4)
> (5/31) Installing bash (4.3.46-r5)
> Executing bash-4.3.46-r5.post-install
> (6/31) Installing ca-certificates (20161130-r1)
> (7/31) Installing libssh2 (1.7.0-r2)
> (8/31) Installing libcurl (7.56.1-r0)
> (9/31) Installing curl (7.56.1-r0)
> (10/31) Installing openjdk8-jre-lib (8.121.13-r0)
> (11/31) Installing java-common (0.1-r0)
> (12/31) Installing libffi (3.2.1-r2)
> (13/31) Installing libtasn1 (4.9-r2)
> (14/31) Installing p11-kit (0.23.2-r1)
> (15/31) Installing p11-kit-trust (0.23.2-r1)
> (16/31) Installing java-cacerts (1.0-r0)
> (17/31) Installing libjpeg-turbo (1.5.1-r0)
> (18/31) Installing krb5-conf (1.0-r1)
> (19/31) Installing libcom_err (1.43.3-r0)
> (20/31) Installing keyutils-libs (1.5.9-r1)
> (21/31) Installing libverto (0.2.5-r0)
> (22/31) Installing krb5-libs (1.14.3-r1)
> (23/31) Installing lcms2 (2.8-r1)
> (24/31) Installing nspr (4.12-r0)
> (25/31) Installing sqlite-libs (3.15.2-r1)
> (26/31) Installing nss (3.28.4-r0)
> (27/31) Installing pcsc-lite-libs (1.8.20-r0)
> (28/31) Installing lksctp-tools (1.0.17-r0)
> (29/31) Installing libgcc (6.2.1-r1)
> (30/31) Installing libstdc++ (6.2.1-r1)
> (31/31) Installing openjdk8-jre-base (8.121.13-r0)
> Executing busybox-1.25.1-r0.trigger
> Executing ca-certificates-20161130-r1.trigger
> Executing java-common-0.1-r0.trigger
> OK: 81 MiB in 42 packages
> BusyBox v1.25.1 (2016-10-26 16:15:20 GMT) multi-call binary.
> 
> Usage: mkdir [OPTIONS] DIRECTORY...
> 
> Create DIRECTORY
> 
>         -m MODE Mode
>         -p      No error if exists; make parent directories as needed
> Removing intermediate container 39f643abb838

I don't really understand the reason of this error ... the syntax is correct.
I have bypassed it by putting env variable directly in the build but this is not a correct way.
cheers,

**Comment by BlazejT** [comment]
Hi @omerlin 

Docker image build, as designed, should work the same way across different host distributions. If you haven't done any typo or mistake in environments and/or commands, it should work.

How did you run it and how your .env file looks like?
