### ISSUE TITLE
Why is there no one-agent configured in the Collector image?

### ISSUE THREAD

**Issue by tutnes** [Dynatrace/Dynatrace-AppMon-Docker#8]
Why is there no one-agent configured in the Collector image?

I see that port 9999 gets exposed, but not port 8042. 

Any perticular reason?

**Comment by metmajer** [comment]
Tarjei, great suggestion. Please feel free to provide a pull request.

**Comment by MarcinZejer** [comment]
Already implemented, variable APPMON_ONEAGENT_NONSSL_PORT
